
const UserHome = () => {
    return (
        <div>
            <h2 className="text-4xl">I am user home Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nulla dolorem similique corrupti. Repellendus totam soluta provident sequi recusandae aperiam excepturi nemo impedit, fuga alias ut. Dolorum recusandae sed quia architecto accusamus nihil eaque ratione, et velit eos vel molestias rem omnis culpa enim a! Dolorum, voluptatibus voluptates! Nisi est at ipsum reprehenderit recusandae, facilis minima culpa dignissimos quas praesentium ullam iure fuga corrupti, possimus repellat laudantium aperiam voluptatibus tempore corporis alias soluta dolore. Impedit dignissimos explicabo sed vel sapiente minima, harum vitae odit dolorum delectus facilis asperiores soluta enim corporis. Reiciendis vitae libero a labore rem necessitatibus facilis ex! Illo fuga ducimus earum! Libero repudiandae ipsa quam ut aperiam, praesentium quidem tenetur quos, similique vitae saepe at eius, rerum tempore? Perferendis molestiae similique vitae! Pariatur ullam quis sit a eos voluptas quas libero perferendis commodi nihil magni rem eaque, aut hic sint culpa voluptatum consectetur iste dignissimos. Sunt cumque ea sed suscipit tenetur qui, totam beatae impedit dolore minima maxime quaerat libero illo aliquam, quis laboriosam velit quibusdam reprehenderit quo. Repellendus harum similique esse suscipit nihil exercitationem, aspernatur dolorum distinctio, voluptates quia ut iusto facilis asperiores voluptatem! Itaque sint quas accusamus eaque at minima numquam nobis, esse molestiae similique minus totam sequi nihil eligendi fugiat, provident atque blanditiis, voluptas culpa veritatis nisi quos? Impedit commodi esse fugit inventore harum iusto voluptatem temporibus consequuntur. Expedita accusantium ipsam voluptatibus suscipit doloremque incidunt asperiores aliquam maiores sapiente sed, minus facere quae magnam porro iusto delectus aliquid repellat quod recusandae ex provident. Magnam voluptatum perferendis veritatis? Vitae soluta optio, et assumenda vero minima. Eos, cumque debitis inventore laboriosam doloremque repellendus est? Quae veritatis tempore repellendus asperiores fuga rem, laborum dicta deserunt iste distinctio! Nesciunt repudiandae dicta cupiditate omnis eos exercitationem eligendi vero. Soluta nobis vel ea perspiciatis dolor officiis provident tenetur iusto odit architecto.</h2>
        </div>
    );
};

export default UserHome;